### ISSUE TITLE
Castamatic podcast player for iOS

### ISSUE THREAD

**Issue by francosolerio** [good/openweb#16]
Please would you consider adding Castamatic in the podcast player section? It's based on the open web: the user can subscribe both choosing from the iTunes search API and by entering any valid podcast feed URL.

[https://itunes.apple.com/it/app/castamatic-podcast-player/id966632553](https://itunes.apple.com/it/app/castamatic-podcast-player/id966632553)

**Comment by good** [comment]
Done! Thanks for the idea.
