### ISSUE TITLE
NewsWave - RSS Reader

### ISSUE THREAD

**Issue by MarcMV** [good/openweb#35]
Recently released, twitter-style RSS app: 

https://newswaveapp.com

Some quick mentions:
https://bit.ly/2RtGsEo
https://twitter.com/johnnybirk/status/1142224391566061569
https://twitter.com/brentsimmons/status/1122944189854044163

I'm a bit biased as I'm the developer though :)

**Comment by good** [comment]
Nice one, thanks for the suggestion. I added it today.
