### ISSUE TITLE
Add Postbox

### ISSUE THREAD

**Issue by shermandickman** [good/openweb#48]
@good We would love to participate! We develop an email app called Postbox 7 and the website is:
https://www.postbox-inc.com

* Our company doesn't read or store your email messages or passwords
* We do not implement features that invade your privacy
* We warn you if someone is trying to track your behavior 
* We help detect potential phishing and malware attacks
* Free OpenPGP encryption through Enigmail, a 3rd-party Labs Project

We're transparent about the data we do collect and provide easy ways to opt-out:
https://support.postbox-inc.com/hc/en-us/articles/202466840-What-Data-Does-Postbox-Inc-Collect-

Thanks for your consideration!

**Comment by good** [comment]
Hey Sherman. I added Postbox this morning. Thanks for the suggestion, and sorry for the delay.
