### ISSUE TITLE
Expanding the Podcasting category?

### ISSUE THREAD

**Issue by splorp** [good/openweb#61]
There are a number of audio apps (for playing, streaming, recording, and editing) that could potentially be added to the site, including Iconfactory’s [Triode](https://triode.app/) and mStream (#38).

Should these be included under the _Podcasting_ category, expanding the subhead to something like _Audio, Streaming & Podcasting_? Or should we start a new category specifically for _Audio & Video_ apps?

Thoughts?

**Comment by aezell** [comment]
I went to the Podcasting category specifically looking for tools to record, edit, configure, etc. podcasts. I think they are different enough interests that Podcast Creation and Podcast Listening might be two separate categories.

**Comment by good** [comment]
I love the idea of expanding a bit here. Podcasting as one category, and Audio & Video as another? That seems sensible. Would you be up for adding that?

**Comment by aezell** [comment]
@good I've added a PR with a stab at this.

**Comment by aezell** [comment]
Looking now at the original issue, those seem to be about consumption. I focused only on creation. I wonder if that's a big enough difference. Happy to include the items listed above but I think other consumption apps would bear adding as well.
