### ISSUE TITLE
Suggestion: Include Scrivener in 'Text & Writing'

### ISSUE THREAD

**Issue by luxlogica** [good/openweb#65]
If you are a professional writer, and you need a tool that will actually help research, plan and deliver your content (no matter what your writing process might be), there is simply nothing that comes close to **[Scrivener](https://www.literatureandlatte.com/scrivener/)**. It has been the de facto standard for professional writing for well over a decade, and the tool that all others are compared to. It just so happen to be developed by indie developers - who are also writers themselves.

**Comment by good** [comment]
Great idea. Just added it.
